import { styled } from "@/styles";
import Head from "next/head";

const Button = styled("button", {
  backgroundColor: "$green500",
  borderRadius: 4,
  border: 0,
  padding: "4px 8px",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Iginite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button>Enviar</Button>
      </main>
    </>
  );
}
