import { HomeContainer, Product } from "@/styles/pages/home";
import Head from "next/head";
import Image from "next/image";
import camisa1 from "../assets/camisa1.png";
import camisa2 from "../assets/camisa2.png";
import camisa3 from "../assets/camisa3.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Iginite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <Product>
          <Image src={camisa1} alt="" width={520} height={480} />

          <footer>
            <strong>Camisa X</strong>
            <span>R$ 79,90</span>
          </footer>
        </Product>

        <Product>
          <Image src={camisa2} alt="" width={520} height={480} />

          <footer>
            <strong>Camisa X</strong>
            <span>R$ 79,90</span>
          </footer>
        </Product>
      </HomeContainer>
    </>
  );
}
